version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx4g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
      GRADLE_OPTS: -Dorg.gradle.daemon=true
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Add google-services.json
          command: echo $GOOGLE_SERVICES_KEY | base64 -di > app/google-services.json
      - run:
          name: Add android.jks
          command: echo $KEYSTORE_FILE | base64 -di > app/android.jks
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run clean
          command: ./gradlew clean
      - run:
          name: Run assembleProdRelease
          command: ./gradlew assembleProdRelease
      - store_artifacts:
          path: app/build/outputs/apk/dev/debug
          destination: reports
      - store_test_results:
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
workflows:
  version: 2
  TestCI:
    jobs:
      - build